### ISSUE TITLE
Suggestion | PerWorldCommands

### ISSUE THREAD

**Issue by ZZWILLIAMXXTrue** [HimbeersaftLP/HideCommands#2]
Can you make it possible to hide commands in certain worlds?

**Comment by HimbeersaftLP** [comment]
I wanted to keep the plugin as simple as possible, but I can see that that'd be a very useful feature (for example to show the plot command only in plot worlds).
Can you give me a suggestion how you would like that option to be configured in the config?

**Comment by HimbeersaftLP** [comment]
\*cough\* \*cough\*

**Comment by Radledazzler** [comment]
Yess please add support for multiple worlds :) I need this because I don’t want people to know that they can do /fly in skywars or duels or kit pvp plz add this :)

**Comment by HimbeersaftLP** [comment]
@Radledazzler 
I wanted to keep the plugin as simple as possible, but I can see that that'd be a very useful feature (for example to show the plot command only in plot worlds).
Can you give me a suggestion how you would like that option to be configured in the config?

**Comment by iFanatic6** [comment]
Can you hide when someones joins or when somebody’s kills?

**Comment by HimbeersaftLP** [comment]
@iFanatic6 That is completely out of the scope of this plugin.
CustomAlerts is a popular plugin for this purpose: https://poggit.pmmp.io/p/customalerts

**Comment by mrpwes** [comment]
@HimbeersaftLP 
config.yml
```
config-version:
Mode:                                                 #AllInOne or PerWorld
AllInOne:                                             #HideCommands if you choose AllInOneMode
 hidecmds:


PerWorld: enable/disable                    #HideCommands if you choose PerWorld Mode
[World]:
  hidecmds:

[Worlds]:
 hidecmds:
```

**Comment by mrpwes** [comment]
@HimbeersaftLP 
config.yml
```yml
config-version:
Mode: AllInOne                                              #AllInOne or PerWorld
AllInOne: enable                                            #HideCommands if you choose AllInOne Mode
 hidecmds:
          -gamemode
          -time
          -shazam

PerWorld: disable                                           #HideCommands if you choose PerWorld Mode
 [World]:
  hidecmds:

 [Worlds]:
  hidecmds:
```

**Comment by HimbeersaftLP** [comment]
Thank you for the suggestion, but what if I want to blacklist in one world and whitelist in another? @mrpwes

**Comment by mrpwes** [comment]
@HimbeersaftLP 
config.yml
```yml
config-version:

#Mode can be either "blacklist" or "whitelist"
#whitelist mode will only show the commands specified below and hide all others
#blacklist mode will hide the commands specified below and show all others
#Mode1 can be either "allinone" or "perworld"
#allinone mode will provide one hide commands for all worlds
#perworld mode will support many worlds you want
Mode1: allinone                                              #allinone or perworld
AllInOne: enable                                            #HideCommands if you choose AllInOne Mode
Mode: blacklist
 hidecmds:
          -gamemode
          -time
          -shazam

PerWorld: disable                                           #HideCommands if you choose PerWorld Mode
Mode: blacklist
 [World]:
  hidecmds:

 [Worlds]:                                                  #You can add more Worlds if you want to
 Mode: blacklist
  hidecmds:
```
